
org.slf4j.simpleLogger.defaultLogLevel=info

org.slf4j.simpleLogger.log.com.example.nhom49_webbansanphamchamsoctoc=debug
org.slf4j.simpleLogger.log.org.jdbi=warn
org.slf4j.simpleLogger.log.com.mysql=warn

org.slf4j.simpleLogger.showShortLogName=true

org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss

org.slf4j.simpleLogger.showThreadName=true
